Enable securityContext for pod and container
rstudio/helm pull request #198
Opened 2022-05-12 17:47 UTC by rodrigobrim

As part of our plan to run the container as an ordinary user, we need to change the default `container[0].securityContext.privileged` from true to false.

We also need the ability to change the pod security context, allowing the `fsGroup` storage parameter.

2022-05-12 19:02 UTC, jonyoder approved these changes
Looks good to me. It would probably be wise to have someone more familiar with helm (and more involved with this repo) to also take a look.

2022-05-12 19:15 UTC, rodrigobrim commented
> Looks good to me. It would probably be wise to have someone more familiar with helm (and more involved with this repo) to also take a look.

Sure. Aaron and Cole added.

2022-05-12 19:48 UTC, colearendt requested changes
Looks good! I didn't realize we still run this as privileged. A couple of things:

- it looks like you mixed up the convention with the other products. You have `pod.securityContext` setting the context on the container, and `securityContext` setting the context on the pod? I will need to take a deeper look at the other charts, but I think this is mixed up here (even the docs?)

- Also, if we are keeping the default as `privileged: true`, we should put that in the default values, rather than set the default in an `else` in the helm chart

2022-05-12 21:53 UTC, rodrigobrim commented
> Looks good! I didn't realize we still run this as privileged. A couple of things:
> 
> * it looks like you mixed up the convention with the other products. You have `pod.securityContext` setting the context on the container, and `securityContext` setting the context on the pod? I will need to take a deeper look at the other charts, but I think this is mixed up here (even the docs?)
> * Also, if we are keeping the default as `privileged: true`, we should put that in the default values, rather than set the default in an `else` in the helm chart

They are not totally mixed. In the pod.securityContext there's no privileged config. In the container.securityContext, there's no fsGroup config. They are independent in some aspects.

About the if, I'll set it in the values.

2022-05-13 01:49 UTC, colearendt commented
Oh no, my point is that you are using `pod.securityContext` as "container security context" and `securityContext` as "pod security context." Those should be reversed 😄 

Expected:
- `securityContext`: container security context
- `pod.securityContext`: pod security context

2022-05-13 14:57 UTC, atheriel requested changes

2022-05-13 14:57 UTC, atheriel commented on charts/rstudio-pm/values.yaml
> +securityContext:
I've looked at [various](https://github.com/kubernetes/ingress-nginx/blob/24b8e32b088bec15e1f40deab8fefc8bd1b6c2da/charts/ingress-nginx/values.yaml#L825) [community](https://github.com/grafana/helm-charts/blob/f942ba605f8780518b6ac7f52eb68fb275c02e8b/charts/grafana/values.yaml#L101) charts and the convention is to use `containerSecurityContext` for this to disambiguate. Let's follow that convention.

2022-05-13 17:13 UTC, atheriel approved these changes
This looks fine to me now. @colearendt do you have an opinion on whether `containerSecurityContext` should be top-level or nested under `pod`? Are these changes in line with what you expected?

2022-05-13 19:36 UTC, colearendt approved these changes
I do like that convention within `pod`, I think, and consistency w/ the community is a win! We should take a follow-up issue to move our other charts towards this pattern.

2022-05-16 12:50 UTC, merged